### ISSUE TITLE
Remove redundant element styles

### ISSUE THREAD

**Issue by progers** [stevenbfine/snap-it#28]
Currently all styles from getComputedStyle are listed for each element but thats very verbose. One way to reduce this would be to make a second pass over the snapped document and compare getComputedStyle with and without the style attribute set.

**Comment by chrishtr** [comment]
The approach suggested by progers will make snap-it output styles relative to the current user agent's
default style sheet, which may (and does) vary by browser. Instead, I suggest using the same approach
to get the default style, and then put that in an inline style tag like this:
- {
  <default styles>
  }

You might have to do this multiple times, for each type of different element (div vs span, etc).

Getting access to the user agent style sheet would make this a lot easier. Perhaps that's something
that should be added to the extension API?

**Comment by progers** [comment]
How important is cross-browser support? I can think of two pretty difficult issues if it is important:
1) Many real-world pages work differently based on the user agent, whether for binary size (no redundant styles), quirks due to javascript/jquery, etc. Our hands are tied in these situations.
2) Our approach to getting style is getComputedStyle which will return many webkit-prefixed styles.

**Comment by chrishtr** [comment]
I think progers is probably right. cross-browser is too hard for now, let's get it working for Chrome. For that, the simplest method is what progers suggested in the first comment.
