### ISSUE TITLE
Need a super cool icon

### ISSUE THREAD

**Issue by progers** [stevenbfine/snap-it#32]
These have an apache2 license so I think you can just use them for free:
https://design.google.com/icons/#ic_camera_enhance
https://design.google.com/icons/#ic_photo_camera

The folks who made those icons actually work in our office (opposite corner) if you wanted something customized. You can also download the svg and open it in inkscape to adjust the colors.

**Comment by stevenbfine** [comment]
Since there is no background on the current icon, it doesn't show up for some chrome themes.

**Comment by progers** [comment]
Fixed with https://github.com/stevenbfine/snap-it/pull/61
