### ISSUE TITLE
Resolve relative URL paths for images to fully-qualified ones

### ISSUE THREAD

**Issue by chrishtr** [stevenbfine/snap-it#4]
Filing this bug to make sure it gets addressed. Not sure if the bug is present, but I presume so:

When snapshotting a page at http://example.com/foo/bar/page.html, make sure to record image URLs within it
with fully qualified names. For example, page.html might have this:

<img src="subdirectory/image.png"></image>

This should be snapshotted as:

<img src="http://example.com/foo/bar/subdirectory/image.png"></image>

The same will need to be done for any CSS styles that reference URLs. For example: 

background: url("subdirectory/background.png");

needs to be rewritten as:

background: url("http://example.com/foo/bar/subdirectory/image.png");

One code reference:

http://james.padolsey.com/snippets/getting-a-fully-qualified-url/

**Comment by stevenbfine** [comment]
I created a function that will convert a partial url to a URL object, (which contains the fully qualified url) based on the link you provided.

For CSS styles,  I retrieve them all using window.getComputedStyle, which seems to return only absolute urls.  (Section 3.4.1 of https://www.w3.org/TR/css-values/)

**Comment by stevenbfine** [comment]
window.getComputedStyle does indeed return the absolute url.  It will return the computed value for urls.  See Notes section: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle.  Per https://www.w3.org/TR/css-values/, section 3.4.1 the computed value of a url is the absolute url.

**Comment by stevenbfine** [comment]
@chrishtr can I close this issue, or should I change the way I am getting computing fully qualified urls?

**Comment by stevenbfine** [comment]
@chrishtr can I close this issue?  Or should I change the way I get the fully qualified URL?

**Comment by chrishtr** [comment]
Sounds fine to close. Assume it's tested?

**Comment by stevenbfine** [comment]
I've got one test for it.
